### ISSUE TITLE
Pin nginx, staff-api and edge tags

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#31]
Update Image references [currently in use](https://github.com/place-labs/partner-environment/blob/a130a53591359db23c248c14a702e2e4ed7441bd/.env#L33-L44) below to use immutable tags...

- [x] `nginx`
- [x] `staff-api` 
- [x] `edge`

Default config (and any upstream packaging) should be updated to use platform versions.

**Comment by caspiano** [comment]
`staff-api` tag is dependent on PlaceOS/PlaceOS#86
