### ISSUE TITLE
Environment fails to start due to "Address already in use"

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#33]
Seperate users have reported they have run into issues since the recent re-addition of static IP's to this environment.

When starting the environment the following error occurs:
```
ERROR: for api  Cannot start service api: Address already in use
ERROR: Encountered errors while bringing up the project.
```
The service that encounters the conflict varies.

No address conflict appears to exist either on this compose config, or on NIC's on the machine they are running (as reported).

Stopping and removing all containers does not resolve, however changing the IP address of the impacted container does.

**Comment by viv-4** [comment]
Is this occurring for you on the latest of master? @jeremy-west
