### ISSUE TITLE
Runtime environment overridden by `.env`

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#38]
**Describe the bug**
Environment variables declared within `.env` override the state of the runtime environment within the install script (and likely others). This is the inverse of normal `.env` file behaviour, including within docker-compose (runtime env overrides `.env`).

**To Reproduce**
```bash
$ export PLACE_DOMAIN=example.com
$ ./install

...

=== Setup complete. Login to https://localhost:8443/backoffice/ ...
```

**Expected behavior**
Environment variables that exist should take precedence over those declared in `.env`.

**Additional context**
Cause: https://github.com/place-labs/partner-environment/blob/47f6ca7e39d1ef90b3eb423cabce3eba6b598c7e/install#L52

**Comment by caspiano** [comment]
I believe this will be closed by #53
