### ISSUE TITLE
Limit exposed services

### ISSUE THREAD

**Issue by kimburgess** [place-labs/partner-environment#39]
**Is your feature request related to a problem? Please describe.**
As development machines often run a number of different services on localhost, it would be useful to limit the number of ports used by this environment to reduce the chance of a conflict.

**Describe the solution you'd like**
Expose only nginx on localhost, with all other services being available on the docker network only.

**Describe alternatives you've considered**
Performing dynamic port allocation on start, however this introduces a lot of complexity.

**Additional context**
If services do require direct access for development purposes, this can be added to environments requiring this. A sensible default appears to be to start with the minimum exposes only.

**Comment by jcit1** [comment]
Hi Kim.  Yes especially noticed that port 8082 and 8089 are pretty much in use on most Windows Dev machines.
