### ISSUE TITLE
Improve container healthchecks

### ISSUE THREAD

**Issue by caspiano** [place-labs/partner-environment#61]
Improve the quality of healthchecks in the `docker-compose.yml`.

This can be achieved via setting [`healthcheck` params](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) to accomodate this, specifically `start_period`.

Previously containers has explicit dependencies between one another, however, they have been dropped as this syntax has been dropped as of the compose standard 3.

**Comment by viv-4** [comment]
nginx and postgres healthchecks added in https://github.com/place-labs/partner-environment/pull/102
