### ISSUE TITLE
on fresh install, successful login redirects back to login page. cannot load backoffice

### ISSUE THREAD

**Issue by w-le** [place-labs/partner-environment#85]
**Describe the bug**
on fresh install, successful login redirects back to login page. cannot load backoffice

**Your environment**
partner-environment at e83eaa801db90840196f935e9e7fdee8c79f004c

**To Reproduce**
(Ubuntu 20 via WSL on Windows 10)
```
git clone
./placeos start
```
set the default username
set a password

visit https://localhost:8443/backoffice
attempting to login with that user specified username and password actually 401s (a seperate bug)
but logging in with a previous default support@place.tech:development works 202
BUT after forwarding to /backoffice, we are redirected back to /login

I think that the behaviour started after this change: https://github.com/PlaceOS/auth/commit/35258ddfdda2371bddd29cba5600655b8b6a051e

**Comment by w-le** [comment]
wip at branch fix-login, tested ok

**Comment by w-le** [comment]
fix/login branch tested ok on 3 different WSL ubuntu systems

**Comment by stakach** [comment]
added comments to PlaceOS/auth#47
