### ISSUE TITLE
feat: allow some services to be disabled by the end user as part of the installation

### ISSUE THREAD

**Issue by w-le** [place-labs/partner-environment#97]
Most devs won't need these services:

influx
chronograf
mosquitto
source

and some like influx may be cpu/ram intensive.
Let's give an option for NOT installing and initializing those services, as part of the `placeos start` script.

**Comment by w-le** [comment]
I'll assign this to Rolando `rdiaz` after he joins place-labs

**Comment by caspiano** [comment]
An approach like that of https://github.com/place-labs/partner-environment/pull/49 can be taken here.

**Comment by w-le** [comment]
Oh sorry I only just saw that Caspian has already made this enhancement

**Comment by w-le** [comment]
I'll close this after #99 is, awesome change thanks caspiano
